config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit]
    resources :orders, except: [:edit, :update, :destroy]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show]
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items, dependent: :destroy
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end
  
  def index
    @items = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品詳細の変更内容に不備があります。"
      render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_no_cart.html.erb
<p>お客様のショッピングカートに商品はありません。</p>
<p><%= link_to "商品一覧", items_path, class: "btn-link" %>から商品をお探し下さい。</p>

app/views/admin/items/edit.html.erb
<div class="container">
  <h4 class="mx-5 my-5"><strong>商品編集</strong></h4>
  <div class="row">
    <div class="col-8 mb-5 mx-auto justify-content-center">
      <%= form_with model: @item, url: admin_item_path do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像, class: "form_label" %></th>
            <td><%= f.file_field :image, class: "mb-3 ml-3" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名, class: "form_label" %></th>
            <td><%= f.text_field :name, class: "form-control mb-3" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明, class: "form_label" %></th>
            <td><%= f.text_area :introduction, size: "50x5", class: "form-control mb-3" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :税抜価格, class: "form_label" %></th>
            <td><%= f.text_field :price %>円</td>
          </div>
        </tr>
        </table>
        <br>
          <div class="form-action d-flex justify-content-around">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="mx-5 my-5"><strong>商品一覧</strong></h4>
    </div>
    <div class="col text-right my-5">
      <%= link_to new_admin_item_path do %>
        <i class="fa-solid fa-circle-plus fa-2xl"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admin_item_path(item.id) %></td>
              <td><%= item.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h4 class="mx-5 my-5"><strong>商品新規登録</strong></h4>
  <div class="row">
    <div class="col-8 mb-5 mx-auto justify-content-center">
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <table>
          <tr>
            <div class="field">
              <th><%= f.label :商品画像, class: "form_label" %></th>
              <td><%= f.file_field :image, accept: "image/*", class: "mb-3 ml-3" %></td>
            </div>
          </tr>
          <tr>
            <div class="field">
              <th><%= f.label :商品名, class: "form_label" %></th>
              <td><%= f.text_field :name, placeholder: "商品名", class: "form-control mb-3" %></td>
            </div>
          </tr>
          <tr>
            <div class="field">
              <th><%= f.label :商品説明, class: "form_label" %></th>
              <td><%= f.text_area :introduction, size: "50x5", placeholder: "ここに説明文を記述します", class: "form-control mb-3" %></td>
            </div>
          </tr>
          <tr>
            <div class="field">
              <th><%= f.label :税抜価格, class: "form_label" %></th>
              <td><%= f.text_field :price, placeholder: "1000" %>円</td>
            </div>
          </tr>
        </table>
          <br>
            <div class="action d-flex justify-content-around">
              <%= f.submit "新規登録", class: "btn btn-success" %>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4 class="mx-5 my-5"><strong>商品詳細</strong></h4>
  <div class="row">
    <div class="col">
      <%= image_tag @item.get_image(500,500) %>
    </div>
    <div class="col">
      <table class="table">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>税込価格<br>(税抜価格)</th>
          <td><%= @item.with_tax_price %> (<%= @item.price %>) 円</td>
        </tr>
      </table>
      <div class="d-flex justify-content-center">
        <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>