config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit]
    resources :orders, except: [:edit, :update, :destroy]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show]
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
         
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customers_path
    else
      render 'edit'
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4 class="mx-5 my-4"><strong><%= @customer.last_name %><%= @customer.first_name %></strong>さんの<strong>会員情報編集</strong></h4>
  <div class="row">
    <div class="col-8 mb-5 mx-5">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
      <table>
        <tr>
          <div class="field">
            <th><%= f.label :会員ID %></th>
            <td><%= @customer.id %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :氏名 %></th>
            <td>
              <div class="row">
                <div class="col">
                  <%= f.text_field :last_name, class: "form-control mb-2" %>
                </div>
                <div class="col">
                  <%= f.text_field :first_name, class: "form-control mb-2" %>
                </div>
              </div>
            </td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :フリガナ %></th>
            <td>
              <div class="row">
                <div class="col">
                  <%= f.text_field :last_name_kana, class: "form-control mb-2" %>
                </div>
                <div class="col">
                  <%= f.text_field :first_name_kana, class: "form-control mb-2" %>
                </div>
              </div>
            </td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :郵便番号 %></th>
            <td><%= f.text_field :postal_code, class: "form-control mb-2" %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :住所 %></th>
            <td><%= f.text_field :address, class: "form-control mb-2" %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :電話番号 %></th>
            <td><%= f.text_field :telephone_number, class: "form-control mb-2" %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :メールアドレス %></th>
            <td><%= f.text_field :email, class: "form-control mb-2" %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= f.label :会員ステータス %></th>
            <td>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効" %>
     　        <%= f.radio_button :is_deleted, true %>
     　        <%= f.label :is_deleted, "退会" %>
      　     </td>
          </div>
        </tr>
      </table>
      <div class="my-3 d-flex justify-content-center">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h4 class="mx-5 my-5"><strong>会員一覧</strong></h4>
  <div class="row">
    <div class="col-8 mb-5 mx-auto justify-content-center">
      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted %>
                <p class="text-secondary"><strong>退会</strong></p>
              <% else %>
                <p class="text-success"><strong>有効</strong></p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h4 class="mx-5 my-4"><strong><%= @customer.last_name %><%= @customer.first_name %></strong>さんの<strong>会員詳細</strong></h4>
  <div class="row">
    <div class="col-8">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
            <% if @customer.is_deleted %>
              <td class="text-secondary"><strong>退会</strong></td>
            <% else %>
              <td class="text-success"><strong>有効</strong></td>
            <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8 mb-5 d-flex mx-auto justify-content-around">
        <p><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %></p>
        <p><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %></p>
    </div>
  </div>
</div>