config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit]
    resources :orders, except: [:edit, :update, :destroy]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show]
  end
  
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3e3ae661b7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <!--<div class="container">-->
          <% if admin_signed_in? %>
            <%= link_to "NaganoCAKE", admin_root_path, class: "header-title navbar-brand mx-5" %>
          <% else %>
            <%= link_to "NaganoCAKE", root_path, class: "header-title navbar-brand mx-5" %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
      <% elsif customer_signed_in? %>
        <li class="nav-item mx-3 my-3">ようこそ、<%= current_customer.last_name %>さん！</li>
        <li class="nav-item">
          <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary mb-3 mx-3 my-2" %>
        </li>
      <% end %>
            </ul>
          </div>
        <!--</div>-->
      </nav>
    </header>
    <%= yield %>
    <footer class="shadow-sm">
      <!--<div class="fixed-bottom">-->
        <div class="d-flex justify-content-center">
        <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
        <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
        <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
        </div>
        <p class="text-center">© All rights reserved by Infratop.Inc.</p>
      <!--</div>-->
    </footer>
  </body>
</html>